---
# install base packages
# poc version: 0.1b
# date: 27/04/2017

- hosts: dbservers, localhost
  become: yes
  remote_user: ansible
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
  - name: yum update
    yum: name=* state=latest

  - name: install apache packages
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - httpd-devel
    - httpd-tools
    notify: Restart HTTPD

  - name: install postgresql packages
    yum:  name={{ item }} state=present
    with_items:
    - postgresql
    - postgresql-libs

  handlers:
  - name: Restart HTTPD
    service: name=httpd state=restarted
