---
# install base packages
# poc version: 0.1c
# date: 31/05/2017

- hosts: all
  become: yes
  remote_user: ansible
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
  - name: yum update
    yum: name=* state=latest

  - name: install apache packages
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - httpd-devel
    - httpd-tools
    notify: restart apache

  - name: install postgresql packages
    yum:  name={{ item }} state=present
    with_items:
    - postgresql
    - postgresql-libs
    
  - name: install git packages
    yum:  name={{ item }} state=present
    with_items:
    - git
    - perl-Git

  handlers:
  - name: restart apache
    service: name=httpd state=started
