---
# Set SSH key from file
- hosts: dbservers
  become: yes
  remote_user: ansible
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Set SSH key from file
    authorized_key:
     user: oracle
     state: present
     key: "{{ lookup('file', '/home/oracle/.ssh/id_rsa.pub') }}"
