# tasks file for users
- hosts: localhost,dbservers
  become: yes
  remote_user: ansible
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - user:
    name: oracle
    comment: "Oracle User"
    uid: 502
    groups: dba
    shell: /bin/bash
    append: yes
